version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13"
  apt_packages:
    # C++ tools
    - build-essential
    - ninja-build
    # Eigen
    - pkg-config
    # vcpkg
    - curl
    - git
    - tar
    - unzip
    - zip
  jobs:
    pre_create_environment:
      # CMake
      - |
        cmake_dir=`mktemp -d /tmp/cmake.XXXXXXXXXX`
        curl --silent --show-error --fail \
             -L https://github.com/Kitware/CMake/releases/download/v4.2.3/cmake-4.2.3-linux-x86_64.sh \
             --output $cmake_dir/cmake.sh
        chmod u+x $cmake_dir/cmake.sh
        mkdir -p $HOME/.local
        $cmake_dir/cmake.sh --prefix=$HOME/.local --skip-license
      # uv
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      # vcpkg
      - git clone https://github.com/microsoft/vcpkg.git $HOME/vcpkg
      - $HOME/vcpkg/bootstrap-vcpkg.sh -disableMetrics
    create_environment:
      - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    install:
      - |
        VCPKG_ROOT=$HOME/vcpkg
        PATH=$VCPKG_ROOT:$HOME/.local/bin:$PATH
        UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync \
          --link-mode=copy \
          --group docs \
          --config-setting=cmake.args="--preset vcpkg"
